name: ex_d_08_arithmetic CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install
        run: sudo apt-get install build-essential
      - name: build the test
        run: make
      - name: run the test
        run: make check
